# Generated by Django 3.2.5 on 2021-07-05 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowcalc', '0002_resource_resource_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftedresource',
            name='crafting_discipline',
            field=models.CharField(choices=[('ALC', 'Alchemy'), ('ARM', 'Armorsmithing'), ('JWL', 'Jewelcrafting'), ('LTW', 'Leatherworking'), ('NEC', 'Necromancy'), ('RUN', 'Runemaking'), ('STO', 'Stonemasonry'), ('WPN', 'Weaponsmithing'), ('WOO', 'Woodworking')], default='ALC', max_length=3),
        ),
        migrations.AddField(
            model_name='gatherable',
            name='resource_type',
            field=models.CharField(choices=[('W', 'Wood'), ('O', 'Ore'), ('S', 'Stone'), ('L', 'Leather'), ('B', 'Body Parts')], default='W', max_length=1),
        ),
    ]
