# Generated by Django 3.2.5 on 2021-07-05 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowcalc', '0006_alter_resource_components'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='resource_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='resource',
            old_name='resource_rarity',
            new_name='rarity',
        ),
    ]
