# Generated by Django 3.2.5 on 2021-07-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowcalc', '0007_auto_20210705_0918'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gatherable',
            new_name='GatherableResource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='components',
        ),
        migrations.AddField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(default='test', on_delete=django.db.models.deletion.CASCADE, to='crowcalc.craftedresource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='rarity',
            field=models.CharField(choices=[('A', 'Any'), ('C', 'Common'), ('U', 'Uncommon'), ('R', 'Rare'), ('E', 'Epic'), ('L', 'Legendary')], default='C', max_length=1),
        ),
    ]
