# Generated by Django 3.2.5 on 2021-07-05 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowcalc', '0008_auto_20210705_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crowcalc.craftedresource'),
        ),
    ]
