# Generated by Django 3.2.5 on 2021-07-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('craftquests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftingrequest',
            name='crafter',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='craftingrequest',
            name='stats',
            field=models.TextField(blank=True, default="Crafter's choice", null=True),
        ),
    ]
